<?php

namespace App\Support;

class SakExamCatalog
{
    public const PROGRAM = [
        'code' => 'SAK',
        'slug' => 'sak',
        'name' => 'Sertifikasi Ahli Kepabeanan',
        'description' => 'Platform pembelajaran mandiri dan simulasi Computer-Based Test untuk persiapan Sertifikasi Ahli Kepabeanan.',
        'is_active' => true,
    ];

    public static function all(): array
    {
        return [
            1 => [
                'number' => 1,
                'code' => 'SAK-BAB01',
                'slug' => 'bab-01-btki-npkb',
                'title' => 'SAK • Bab 01 • Teknik Klasifikasi Barang Berdasarkan BTKI 2022 & Pembuatan NPKB',
                'token' => 'SAK-BAB01-BTKI',
                'token_hint' => 'SAK-BAB01-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            2 => [
                'number' => 2,
                'code' => 'SAK-BAB02',
                'slug' => 'bab-02-perhitungan-pabean',
                'title' => 'SAK • Bab 02 • Perhitungan Penerimaan Negara & Pemberitahuan Pabean',
                'token' => 'SAK-BAB02-HITUNG',
                'token_hint' => 'SAK-BAB02-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            3 => [
                'number' => 3,
                'code' => 'SAK-BAB03',
                'slug' => 'bab-03-undang-undang-kepabeanan',
                'title' => 'SAK • Bab 03 • Ketentuan dan Konsep dalam Undang-Undang Kepabeanan',
                'token' => 'SAK-BAB03-UUBC',
                'token_hint' => 'SAK-BAB03-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            4 => [
                'number' => 4,
                'code' => 'SAK-BAB04',
                'slug' => 'bab-04-prosedur-ekspor-impor',
                'title' => 'SAK • Bab 04 • Sistem & Prosedur Ekspor, Impor, serta Rezim Khusus',
                'token' => 'SAK-BAB04-PROS',
                'token_hint' => 'SAK-BAB04-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            5 => [
                'number' => 5,
                'code' => 'SAK-BAB05',
                'slug' => 'bab-05-fasilitas-tpb-kite-roo',
                'title' => 'SAK • Bab 05 • Fasilitas Kepabeanan, TPB, KITE, & ROO',
                'token' => 'SAK-BAB05-FASTPB',
                'token_hint' => 'SAK-BAB05-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            6 => [
                'number' => 6,
                'code' => 'SAK-BAB06',
                'slug' => 'bab-06-klasifikasi-wco',
                'title' => 'SAK • Bab 06 • Sistem Klasifikasi Barang Secara Konseptual & Harmonisasi WCO',
                'token' => 'SAK-BAB06-WCO',
                'token_hint' => 'SAK-BAB06-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            7 => [
                'number' => 7,
                'code' => 'SAK-BAB07',
                'slug' => 'bab-07-nilai-pabean-wto',
                'title' => 'SAK • Bab 07 • Sistem Nilai Pabean Standar WTO',
                'token' => 'SAK-BAB07-WTO',
                'token_hint' => 'SAK-BAB07-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            8 => [
                'number' => 8,
                'code' => 'SAK-BAB08',
                'slug' => 'bab-08-pembayaran-penagihan',
                'title' => 'SAK • Bab 08 • Pembayaran, Penagihan, Pengembalian, Jaminan Pabean, & BTD/BDN/BMN',
                'token' => 'SAK-BAB08-KEUBMN',
                'token_hint' => 'SAK-BAB08-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            9 => [
                'number' => 9,
                'code' => 'SAK-BAB09',
                'slug' => 'bab-09-keberatan-banding',
                'title' => 'SAK • Bab 09 • Keberatan dan Banding di Bidang Kepabeanan',
                'token' => 'SAK-BAB09-BANDING',
                'token_hint' => 'SAK-BAB09-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            10 => [
                'number' => 10,
                'code' => 'SAK-BAB10',
                'slug' => 'bab-10-lartas-insw-haki',
                'title' => 'SAK • Bab 10 • Larangan & Pembatasan, INSW, & Perlindungan HAKI',
                'token' => 'SAK-BAB10-INSW',
                'token_hint' => 'SAK-BAB10-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            11 => [
                'number' => 11,
                'code' => 'SAK-BAB11',
                'slug' => 'bab-11-pde-ceisa',
                'title' => 'SAK • Bab 11 • Pertukaran Data Elektronik & Arsitektur CEISA 4.0',
                'token' => 'SAK-BAB11-CEISA',
                'token_hint' => 'SAK-BAB11-****',
                'exam_type' => 'chapter',
                'duration_seconds' => 1200,
                'pass_score' => 65.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'full_explanation',
                'is_active' => true,
            ],
            12 => [
                'number' => 12,
                'code' => 'SAK-BAB12',
                'slug' => 'bab-12-tryout-akbar',
                'title' => 'SAK • Bab 12 • Simulasi Tryout Akbar SAK',
                'token' => 'SAK-BAB12-TRYOUT',
                'token_hint' => 'SAK-BAB12-****',
                'exam_type' => 'tryout',
                'duration_seconds' => 9000,
                'pass_score' => 60.00,
                'attempt_limit' => null,
                'randomize_questions' => false,
                'randomize_options' => false,
                'result_review_mode' => 'score_only',
                'is_active' => true,
            ],
        ];
    }

    public static function find(int $number): ?array
    {
        return self::all()[$number] ?? null;
    }

    public static function count(): int
    {
        return count(self::all());
    }
}
